<a href="https://colab.research.google.com/github/varshasisodiya16-arch/first-repository/blob/main/movie_api_(2).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import requests

In [2]:
requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

In [3]:
requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

In [4]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page=1')

In [5]:
df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

In [6]:
df.head()

,id,title,overview,release_date,popularity,vote_average,vote_count
0,1560520,Batman: Knightfall Part 1: Knightfall,"Arkham Asylum has been destroyed, and all its ...",2026-06-23,35.4988,9.100,492
1,980431,Avatar Aang: The Last Airbender,"Avatar Aang, the world's last Airbender, learn...",2026-07-24,59.0299,9.036,1393
2,1007757,Swapped,"A small woodland creature and a majestic bird,...",2026-05-01,39.3270,8.844,2281
3,1632181,Accidental Partners,Two women discover they were both scammed by t...,2026-03-12,12.8826,8.814,404
4,1311031,Demon Slayer: Kimetsu no Yaiba Infinity Castle,The Demon Slayer Corps are drawn into the Infi...,2025-07-18,45.3120,8.801,2352

In [7]:
df = pd.DataFrame()

In [8]:
df

Empty DataFrame
Columns: []
Index: []

In [9]:
all_dfs = [] # create empty list

In [10]:
#using for loop keep all data in all_dfs dataframe using append method
for i in range(1, 429):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=8265bd1679663a7ea12ac168da84d2e8&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    all_dfs.append(temp_df) # add to list, not to df

In [11]:
# Final concat outside loop
df = pd.concat(all_dfs, ignore_index=True)

print(df.shape)
print(df.head())

(8560, 7)
        id                                           title  \
0  1560520           Batman: Knightfall Part 1: Knightfall
1   980431                 Avatar Aang: The Last Airbender
2  1007757                                         Swapped
3  1632181                             Accidental Partners
4  1311031  Demon Slayer: Kimetsu no Yaiba Infinity Castle

                                            overview release_date  popularity  \
0  Arkham Asylum has been destroyed, and all its ...   2026-06-23     35.4988
1  Avatar Aang, the world's last Airbender, learn...   2026-07-24     59.0299
2  A small woodland creature and a majestic bird,...   2026-05-01     39.3270
3  Two women discover they were both scammed by t...   2026-03-12     12.8826
4  The Demon Slayer Corps are drawn into the Infi...   2025-07-18     45.3120

   vote_average  vote_count
0         9.100         492
1         9.036        1393
2         8.844        2281
3         8.814         404
4         8.801        2352

In [12]:
#write into CSV
df.to_csv('movies.csv')